### ISSUE TITLE
CI: Github action implementation for /frontend-next

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#27]
## Problem

TogetherCrew is based on micro-services. As the number of micro-services will continue to grow, it is of vital importance to ensure that they follow the same CI pipeline, else developers the quality and speed of delivery of the product will be put at risk.

## Solution
We have already developed a CI pipeline for the TogetherCrew project. Now we need to align our existing repositories to this pipeline.

## Task

- Create a file in the repository .github/workflows/ci.yml
- Paste the following code:

```yml
name: Staging CI/CD Pipeline

on: pull_request

jobs:
  ci:
    uses: TogetherCrew/operations/.github/workflows/ci.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
```

- Confirm that the action has succeeded after opening a pull request.

## Prerequisites
- #26
